// Runs the C++ binary on every workloads/*.txt and bundles the traces into
// web/data/presets.js, so the visualizer works straight from file:// with no
// server and no fetch().
//
//   node tools/gen-traces.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const bin = ['build/mlfq.exe', 'build/mlfq', 'build/Release/mlfq.exe']
  .map((p) => join(root, p)).find(existsSync);
if (!bin) {
  console.error('mlfq binary not found in build/. Build it first (see README).');
  process.exit(1);
}

// display order in the preset dropdown
const order = ['original', 'interactive_vs_batch', 'starvation', 'boost', 'staggered'];
const files = readdirSync(join(root, 'workloads')).filter((f) => f.endsWith('.txt'))
  .sort((a, b) => {
    const ia = order.indexOf(a.slice(0, -4)), ib = order.indexOf(b.slice(0, -4));
    return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
  });

const presets = files.map((f) => {
  const path = join(root, 'workloads', f);
  const trace = JSON.parse(execFileSync(bin, ['--trace', '--workload', path]).toString());
  console.log(`${f}: ${trace.ticks.length} ticks`);
  return { id: f.slice(0, -4), file: `workloads/${f}`, text: readFileSync(path, 'utf8').replace(/\r/g, ''), trace };
});

mkdirSync(join(root, 'web', 'data'), { recursive: true });
writeFileSync(join(root, 'web', 'data', 'presets.js'),
  '// Generated by tools/gen-traces.mjs from the C++ binary. Do not edit.\n' +
  `window.MLFQ_PRESETS = ${JSON.stringify(presets)};\n`);
console.log(`wrote web/data/presets.js (${presets.length} presets)`);
